select 'CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "' || tablename ||
 '"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();'
 from pg_tables where schemaname = 'public';

 -- CUIDADO NAO DEIXAR LOG ENTRAR EM LOOP COM TRIGGER NOS LOGS

CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "OrderLines"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "Carts"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "Users"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "Organizations"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "Orders"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "EggsBatches"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "Products"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "EggsBatchProducts"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "OrderHistory"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "Explorations"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "Certifications"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "Animals"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();
CREATE TRIGGER tr_logs_general AFTER INSERT OR UPDATE OR DELETE ON "AnimalProducts"  FOR EACH ROW EXECUTE PROCEDURE tr_fc_logs();